spring.application.name=demo

server.port=9090

management.endpoints.web.exposure.include=health,info,metrics

spring.datasource.url=jdbc:postgresql://localhost:5432/Rakumo
spring.datasource.username=postgres
spring.datasource.password=DatA_BasE26

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect